### ISSUE TITLE
Missing description in readme

### ISSUE THREAD

**Issue by TheKnarf** [experimental-dustbin/web-shell#1]
The readme doesn't tell what this project is or does. I was led to the project from the [following blog post](https://dev.to/davidk01/ptyjs--xtermjs--shell-in-your-browser-1f9c). Either write something about the project in the readme, or at least link back to the article?

**Comment by davidk01** [comment]
Good idea. Thanks for opening the issue @TheKnarf.

**Comment by zella** [comment]
It would be nice to have instruction how to run it.

**Comment by davidk01** [comment]
@zella I've updated the README with some basic instructions for how to run it.
